#!/usr/bin/python3
import os
import crypt
var=input("enter username")
pswd="hello"+var
if var.isalpha():
    
    code=crypt.crypt(pswd,"22")
    os.system("sudo useradd -m -p "+code+" "+var)
    print("user is created")
else:
	print("Enter a valid username")
